"""SVG output renderer for circle detection results.

Renders detected circles as SVG with CMYK color grouping and optimization.
Based on research findings from card 4janms (step-1-research-svg-output-format).
"""
import math
from typing import List, Tuple, Dict, Optional
from dotmatrix.cluster_pixel_counter import ClusterResult


def cmyk_to_rgb_hex(c: float, m: float, y: float, k: float) -> str:
    """Convert CMYK values to RGB hex color.
    
    Uses standard CMYK→RGB conversion formula with values normalized to 0-100 range.
    
    Args:
        c: Cyan percentage (0-100)
        m: Magenta percentage (0-100)
        y: Yellow percentage (0-100)
        k: Black percentage (0-100)
    
    Returns:
        RGB hex color string (e.g., "#00FFFF")
    
    Examples:
        >>> cmyk_to_rgb_hex(100, 0, 0, 0)
        '#00FFFF'  # Cyan
        >>> cmyk_to_rgb_hex(0, 100, 0, 0)
        '#FF00FF'  # Magenta
    """
    # Normalize to 0-1 range
    c, m, y, k = c / 100, m / 100, y / 100, k / 100
    
    # Standard CMYK → RGB conversion
    r = 255 * (1 - c) * (1 - k)
    g = 255 * (1 - m) * (1 - k)
    b = 255 * (1 - y) * (1 - k)
    
    # Convert to hex
    return f"#{int(r):02X}{int(g):02X}{int(b):02X}"


# Standard CMYK→RGB color mapping for pure inks
CMYK_COLORS = {
    'cyan': cmyk_to_rgb_hex(100, 0, 0, 0),      # #00FFFF
    'magenta': cmyk_to_rgb_hex(0, 100, 0, 0),   # #FF00FF
    'yellow': cmyk_to_rgb_hex(0, 0, 100, 0),    # #FFFF00
    'black': cmyk_to_rgb_hex(0, 0, 0, 100),     # #000000
}


def radius_from_pixels(pixel_count: int) -> float:
    """Calculate circle radius from pixel count.
    
    Args:
        pixel_count: Number of pixels in circle
    
    Returns:
        Radius in pixels
    """
    if pixel_count <= 0:
        return 0.0
    return math.sqrt(pixel_count / math.pi)


def _format_circle(x: float, y: float, radius: float, precision: int = 1) -> str:
    """Format a circle element with limited precision.
    
    Args:
        x: Center X coordinate
        y: Center Y coordinate
        radius: Circle radius
        precision: Decimal places for coordinates (default: 1)
    
    Returns:
        SVG circle element string
    """
    # Format with limited precision for file size optimization
    x_str = f"{x:.{precision}f}".rstrip('0').rstrip('.')
    y_str = f"{y:.{precision}f}".rstrip('0').rstrip('.')
    r_str = f"{radius:.{precision}f}".rstrip('0').rstrip('.')
    
    return f'<circle cx="{x_str}" cy="{y_str}" r="{r_str}"/>'


def _create_svg_header(width: int, height: int) -> str:
    """Create SVG header with metadata.
    
    Args:
        width: Image width in pixels
        height: Image height in pixels
    
    Returns:
        SVG opening tags with metadata
    """
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<title>DotMatrix Circle Detection Output</title>
<desc>Generated by DotMatrix - CMYK Halftone Analysis</desc>'''


def _create_color_group(
    color_name: str,
    color_hex: str,
    clusters: List[ClusterResult],
    scale: float = 1.0,
    precision: int = 1
) -> str:
    """Create SVG group for a specific color with all circles.
    
    Args:
        color_name: Color name (e.g., "cyan", "magenta")
        color_hex: RGB hex color (e.g., "#00FFFF")
        clusters: List of clusters containing this color
        scale: Output scale factor
        precision: Decimal places for coordinates
    
    Returns:
        SVG group element with circles
    """
    if not clusters:
        return ""
    
    # Group header with fill attribute inheritance and blend mode for CMYK mixing
    group_xml = f'<g id="{color_name}-layer" fill="{color_hex}" style="mix-blend-mode: multiply">\n'
    
    # Add circles for each cluster
    for cluster in clusters:
        # Calculate radius from pixel count
        pixel_count = getattr(cluster, color_name, 0)
        if pixel_count <= 0:
            continue
        
        radius = radius_from_pixels(pixel_count) * scale
        if radius < 0.5:  # Skip tiny circles
            continue
        
        x = cluster.x * scale
        y = cluster.y * scale
        
        group_xml += f"  {_format_circle(x, y, radius, precision)}\n"
    
    group_xml += "</g>\n"
    return group_xml


def render_svg(
    clusters: List[ClusterResult],
    image_shape: Tuple[int, int],
    scale: float = 1.0,
    skip_partial: bool = True,
    precision: int = 1,
    optimize: bool = True
) -> str:
    """Render clusters as SVG with CMYK color grouping.
    
    Args:
        clusters: List of detected clusters
        image_shape: (height, width) of original image
        scale: Output scale factor (default: 1.0)
        skip_partial: Skip edge clusters (default: True)
        precision: Decimal places for coordinates (default: 1)
        optimize: Enable optimizations (group fill inheritance, etc.)
    
    Returns:
        Complete SVG document as string
    
    Examples:
        >>> clusters = [ClusterResult(x=100, y=100, cyan=800, black=800, ...)]
        >>> svg = render_svg(clusters, (200, 200))
        >>> assert '<?xml version' in svg
        >>> assert 'cyan-layer' in svg
    """
    h, w = image_shape
    out_w, out_h = int(w * scale), int(h * scale)
    
    # Filter partial clusters if requested
    if skip_partial:
        clusters = [c for c in clusters if not c.partial]
    
    # Group clusters by which colors they contain
    color_clusters: Dict[str, List[ClusterResult]] = {
        'cyan': [],
        'magenta': [],
        'yellow': [],
        'black': [],
    }
    
    for cluster in clusters:
        if cluster.cyan > 0:
            color_clusters['cyan'].append(cluster)
        if cluster.magenta > 0:
            color_clusters['magenta'].append(cluster)
        if cluster.yellow > 0:
            color_clusters['yellow'].append(cluster)
        if cluster.black > 0:
            color_clusters['black'].append(cluster)
    
    # Build SVG document
    svg_parts = [_create_svg_header(out_w, out_h)]
    
    # Add color groups (CMYK order)
    for color_name in ['cyan', 'magenta', 'yellow', 'black']:
        if color_clusters[color_name]:
            group_xml = _create_color_group(
                color_name=color_name,
                color_hex=CMYK_COLORS[color_name],
                clusters=color_clusters[color_name],
                scale=scale,
                precision=precision
            )
            svg_parts.append(group_xml)
    
    svg_parts.append("</svg>")
    
    return '\n'.join(svg_parts)


def render_svg_with_jitter(
    clusters: List[ClusterResult],
    image_shape: Tuple[int, int],
    scale: float = 1.0,
    skip_partial: bool = True,
    precision: int = 1,
    jitter_position: float = 0.0,
    jitter_size: float = 0.0,
    jitter_seed: Optional[int] = None,
    jitter_algorithm: str = 'gaussian'
) -> str:
    """Render clusters as SVG with jitter applied.
    
    This integrates with the jitter system from step 6 (ujhfb4) to enable
    SVG visualization of jittered patterns. Useful for debugging and validation.
    
    Args:
        clusters: List of detected clusters
        image_shape: (height, width) of original image
        scale: Output scale factor
        skip_partial: Skip edge clusters
        precision: Decimal places for coordinates
        jitter_position: Position jitter strength (0-100)
        jitter_size: Size jitter strength (0-100)
        jitter_seed: Random seed for reproducible jitter
        jitter_algorithm: 'gaussian' or 'uniform'
    
    Returns:
        Complete SVG document with jittered circles
    
    Note:
        This is a placeholder for future jitter integration.
        Currently renders without jitter - jitter application deferred to
        SVG post-processing or CSS transforms.
    """
    # TODO: Integrate jitter module when needed for drift validation (step 9)
    # For now, render standard SVG - jitter can be added via SVG transforms
    return render_svg(
        clusters=clusters,
        image_shape=image_shape,
        scale=scale,
        skip_partial=skip_partial,
        precision=precision
    )
